name: Deploy to AWS ECS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build and Push
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050067233.dkr.ecr.us-east-1.amazonaws.com
          docker build -t golden-era .
          docker tag golden-era:latest 975050067233.dkr.ecr.us-east-1.amazonaws.com/golden-era:latest
          docker push 975050067233.dkr.ecr.us-east-1.amazonaws.com/golden-era:latest
      
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster insurancehive-cluster --service goldenera-insurance-web  --force-new-deployment --region us-east-1
